import Link from 'next/link';
import { asc } from 'drizzle-orm';
import { requireSession,can } from '@/platform/auth/current';
import { t } from '@/platform/i18n';
import { getBusinessPartner,listBusinessPartners } from '@/modules/foundation/business-partners';
import { withTenant } from '@/platform/db/client';
import { country } from '@/platform/tables/reference';
import { changeHistory } from '@/platform/change';
import { PartnerForm,type PartnerDraft } from './PartnerForm';
import { getSupplierCompany,supplierCompanyChoices } from '@/modules/foundation/supplier-companies';
import { SupplierCompanyPanel } from './SupplierCompanyPanel';
import { getSupplierPurchasing,supplierPurchasingChoices,DELIVERY_TERMS } from '@/modules/foundation/supplier-purchasing';
import { SupplierPurchasingPanel } from './SupplierPurchasingPanel';
import { getCustomerCompany,customerCompanyChoices } from '@/modules/foundation/customer-companies';
import { CustomerCompanyPanel } from './CustomerCompanyPanel';
import { getCustomerSalesArea,customerSalesAreaChoices } from '@/modules/foundation/customer-sales-areas';
import { CustomerSalesAreaPanel } from './CustomerSalesAreaPanel';
export const dynamic='force-dynamic';
export default async function PartnersPage({searchParams}:{searchParams:Promise<{partner?:string;new?:string;q?:string;history?:string;view?:string;company?:string;org?:string;area?:string}>}){
  const session=await requireSession('/foundation/partners');const client=session.user.client;const params=await searchParams;
  const creating=params.new==='1';const editable=can(session,'FND.PARTNER.MAINTAIN');
  const detail=params.partner?await getBusinessPartner(client,params.partner):null;const rows=!creating&&!detail?await listBusinessPartners(client,params.q??''):[];
  const countries=await withTenant(client,tx=>tx.select({code:country.code,name:country.name}).from(country).orderBy(asc(country.code)));
  const companyView=!!detail&&params.view==='SUPPLIER_COMPANY';
  const customerView=!!detail&&params.view==='CUSTOMER_COMPANY';
  const customerReadable=can(session,'FIN.CUSTOMER.COMPANY.DISPLAY')||can(session,'FIN.CUSTOMER.COMPANY.MAINTAIN')||can(session,'AUDIT.WORKSPACE');
  const customerEditable=can(session,'FIN.CUSTOMER.COMPANY.MAINTAIN');
  const customerActive=detail?.roles.some(role=>role.roleCode==='CUSTOMER'&&role.isActive)??false;
  const purchasingView=!!detail&&params.view==='SUPPLIER_PURCHASING';
  const purchasingReadable=can(session,'PROC.SUPPLIER.PURCHASING.DISPLAY')||can(session,'PROC.SUPPLIER.PURCHASING.MAINTAIN')||can(session,'AUDIT.WORKSPACE');
  const purchasingEditable=can(session,'PROC.SUPPLIER.PURCHASING.MAINTAIN');
  const financialReadable=can(session,'FIN.SUPPLIER.COMPANY.DISPLAY')||can(session,'FIN.SUPPLIER.COMPANY.MAINTAIN')||can(session,'AUDIT.WORKSPACE');
  const financialEditable=can(session,'FIN.SUPPLIER.COMPANY.MAINTAIN');
  const supplierActive=detail?.roles.some(role=>role.roleCode==='SUPPLIER'&&role.isActive)??false;
  const companies=companyView?await supplierCompanyChoices(client,params.company??''):null;
  const company=params.company??companies?.companies[0]?.code??'';
  const choices=companyView&&company!==params.company?await supplierCompanyChoices(client,company):companies;
  const companyRecord=companyView&&financialReadable&&supplierActive&&company?await getSupplierCompany(client,detail!.general.partnerNumber,company):null;
  const purchasingChoices=purchasingView?await supplierPurchasingChoices(client,params.org??''):null;
  const org=params.org??purchasingChoices?.organisations[0]?.code??'';
  const buyingChoices=purchasingView&&org!==params.org?await supplierPurchasingChoices(client,org):purchasingChoices;
  const purchasingRecord=purchasingView&&purchasingReadable&&supplierActive&&org?await getSupplierPurchasing(client,detail!.general.partnerNumber,org):null;
  const customerChoices=customerView?await customerCompanyChoices(client,params.company??''):null;
  const customerCode=params.company??customerChoices?.companies[0]?.code??'';
  const receivableChoices=customerView&&customerCode!==params.company?await customerCompanyChoices(client,customerCode):customerChoices;
  const customerRecord=customerView&&customerReadable&&customerActive&&customerCode?await getCustomerCompany(client,detail!.general.partnerNumber,customerCode):null;
  const salesView=!!detail&&params.view==='CUSTOMER_SALES';
  const salesReadable=can(session,'SALES.CUSTOMER.SALESAREA.DISPLAY')||can(session,'SALES.CUSTOMER.SALESAREA.MAINTAIN')||can(session,'AUDIT.WORKSPACE');
  const salesEditable=can(session,'SALES.CUSTOMER.SALESAREA.MAINTAIN');
  const salesChoices=salesView?await customerSalesAreaChoices(client,params.area??''):null;
  const salesKey=salesChoices?.selected?.key??'';
  const salesRecord=salesView&&salesReadable&&customerActive&&salesChoices?.selected?await getCustomerSalesArea(client,detail!.general.partnerNumber,salesChoices.selected.org,salesChoices.selected.channel,salesChoices.selected.division):null;
  const g=detail?.general;const initial:PartnerDraft=g?{partnerNumber:g.partnerNumber,category:g.category as PartnerDraft['category'],name:g.name,name2:g.name2??'',searchTerm:g.searchTerm??'',country:g.country??'',region:g.region??'',street:g.street??'',city:g.city??'',postalCode:g.postalCode??'',taxNumber:g.taxNumber??'',email:g.email??'',phone:g.phone??'',roles:detail!.roles.filter(r=>r.isActive).map(r=>r.roleCode as 'SUPPLIER'|'CUSTOMER'),isBlocked:g.isBlocked}:{partnerNumber:'',category:'ORGANIZATION',name:'',name2:'',searchTerm:'',country:'KW',region:'',street:'',city:'',postalCode:'',taxNumber:'',email:'',phone:'',roles:['SUPPLIER'],isBlocked:false};
  const history=detail&&params.history==='1'&&(!companyView||financialReadable)&&(!purchasingView||purchasingReadable)&&(!customerView||customerReadable)&&(!salesView||salesReadable)?await withTenant(client,tx=>changeHistory(tx,client,companyView?'supplier_company_code':purchasingView?'supplier_purchasing_org':customerView?'customer_company_code':salesView?'customer_sales_area':'business_partner',companyView?`${detail.general.partnerNumber}/${company}`:purchasingView?`${detail.general.partnerNumber}/${org}`:customerView?`${detail.general.partnerNumber}/${customerCode}`:salesView?`${detail.general.partnerNumber}/${salesKey}`:detail.general.partnerNumber)):[];
  return <div className="mx-auto max-w-6xl space-y-4 p-6"><header className="border-b border-line pb-4"><span className="code text-ink-faint">FND.PARTNER.MAINTAIN</span><div className="flex flex-wrap items-center justify-between gap-3"><h1 className="text-xl font-semibold">{t(creating?'bp.create':'bp.title')}</h1><div className="flex gap-2"><Link className="btn btn-default" href="/config">{t('nav.workbench')}</Link><Link className="btn btn-default" href="/foundation/partners">{t('bp.list')}</Link>{editable&&!creating&&<Link className="btn btn-primary" href="/foundation/partners?new=1">{t('bp.create')}</Link>}</div></div><p className="mt-1 text-sm text-ink-soft">{t('bp.subtitle')}</p></header>
    {params.partner&&!detail&&<p className="panel p-4 text-signal-error">{t('bp.notFound')}</p>}
    {detail&&<><section className="panel grid gap-3 p-3 sm:grid-cols-4"><Summary label={t('bp.number')} value={g!.partnerNumber}/><Summary label={t('bp.name')} value={g!.name||'—'}/><Summary label={t('bp.roles')} value={initial.roles.map(r=>t(`bp.role.${r}`)).join(' · ')||'—'}/><Summary label={t('bp.status')} value={t(`bp.status.${g!.isBlocked?'BLOCKED':g!.generalStatus}`)}/></section><nav className="flex flex-wrap gap-1 border-b border-line pb-3" aria-label={t('bp.segments')}><Link className={`border px-3 py-2 text-sm ${!companyView&&!purchasingView&&!customerView&&!salesView?'border-accent bg-accent-soft text-accent':'border-line'}`} href={`/foundation/partners?partner=${encodeURIComponent(g!.partnerNumber)}`}>{t('bp.general')}</Link>{supplierActive?<Link className={`border px-3 py-2 text-sm ${companyView?'border-accent bg-accent-soft text-accent':'border-line'}`} href={`/foundation/partners?partner=${encodeURIComponent(g!.partnerNumber)}&view=SUPPLIER_COMPANY`}>{t('bp.segment.supplierCompany')}</Link>:<span aria-disabled="true" className="border border-dashed border-line px-3 py-2 text-sm text-ink-faint">{t('sc.roleRequired')}</span>}{supplierActive?<Link className={`border px-3 py-2 text-sm ${purchasingView?'border-accent bg-accent-soft text-accent':'border-line'}`} href={`/foundation/partners?partner=${encodeURIComponent(g!.partnerNumber)}&view=SUPPLIER_PURCHASING`}>{t('bp.segment.purchasing')}</Link>:null}{customerActive?<Link className={`border px-3 py-2 text-sm ${customerView?'border-accent bg-accent-soft text-accent':'border-line'}`} href={`/foundation/partners?partner=${encodeURIComponent(g!.partnerNumber)}&view=CUSTOMER_COMPANY`}>{t('bp.segment.customerCompany')}</Link>:null}{customerActive?<Link className={`border px-3 py-2 text-sm ${salesView?'border-accent bg-accent-soft text-accent':'border-line'}`} href={`/foundation/partners?partner=${encodeURIComponent(g!.partnerNumber)}&view=CUSTOMER_SALES`}>{t('bp.segment.sales')}</Link>:null}{['banks'].map(key=><span key={key} aria-disabled="true" className="border border-dashed border-line px-3 py-2 text-sm text-ink-faint">{t(`bp.segment.${key}`)} · {t('bp.pending')}</span>)}</nav><Link className="text-sm text-accent underline" href={`/foundation/partners?partner=${encodeURIComponent(g!.partnerNumber)}${companyView?`&view=SUPPLIER_COMPANY&company=${encodeURIComponent(company)}`:purchasingView?`&view=SUPPLIER_PURCHASING&org=${encodeURIComponent(org)}`:customerView?`&view=CUSTOMER_COMPANY&company=${encodeURIComponent(customerCode)}`:salesView?`&view=CUSTOMER_SALES&area=${encodeURIComponent(salesKey)}`:''}&history=1`}>{t('bp.history')}</Link></>}
    {(creating||detail)&&!companyView&&!purchasingView&&!customerView&&!salesView&&(editable?<PartnerForm key={creating?'new':g!.partnerNumber} initial={initial} version={g?.version??0} creating={creating} countries={countries}/>:<section className="panel p-4"><p>{t('auth.readOnly',{authority:'FND.PARTNER.MAINTAIN'})}</p>{detail&&<dl className="mt-3 grid gap-2 sm:grid-cols-3">{Object.entries(initial).map(([key,value])=><div key={key}><dt className="field-label">{t(`bp.field.${key}`)}</dt><dd>{Array.isArray(value)?value.join(' · '):String(value??'—')}</dd></div>)}</dl>}</section>)}
    {companyView&&<><form method="get" className="flex items-end gap-2"><input type="hidden" name="partner" value={g!.partnerNumber}/><input type="hidden" name="view" value="SUPPLIER_COMPANY"/><label><span className="field-label">{t('sc.company')}</span><select name="company" defaultValue={company} className="field-input">{choices?.companies.map(row=><option key={row.code} value={row.code}>{row.code} · {row.name}</option>)}</select></label><button className="btn btn-default">{t('sc.selectCompany')}</button></form>
      {!supplierActive?<p className="panel p-4">{t('sc.roleRequired')}</p>:!financialReadable?<p className="panel p-4">{t('auth.missingAuthority',{authority:'FIN.SUPPLIER.COMPANY.DISPLAY'})}</p>:!choices?.selected?<p className="panel p-4">{t('sc.noCompany')}</p>:<SupplierCompanyPanel key={`${g!.partnerNumber}/${company}`} partner={g!.partnerNumber} company={company} initial={{reconciliationAccount:companyRecord?.reconciliationAccount??'',paymentTermsCode:companyRecord?.paymentTermsCode??'',isBlocked:companyRecord?.isBlocked??false,version:companyRecord?.version??0,companyStatus:companyRecord?.companyStatus??'INCOMPLETE'}} chart={choices.selected.chartOfAccounts} currency={choices.selected.currency} accounts={choices.accounts} terms={choices.terms} editable={financialEditable}/>}</>}
    {purchasingView&&<><form method="get" className="flex items-end gap-2"><input type="hidden" name="partner" value={g!.partnerNumber}/><input type="hidden" name="view" value="SUPPLIER_PURCHASING"/><label><span className="field-label">{t('sp.org')}</span><select name="org" defaultValue={org} className="field-input">{buyingChoices?.organisations.map(row=><option key={row.code} value={row.code}>{row.code} · {row.name}</option>)}</select></label><button className="btn btn-default">{t('sp.selectOrg')}</button></form>
      {!supplierActive?<p className="panel p-4">{t('sc.roleRequired')}</p>:!purchasingReadable?<p className="panel p-4">{t('auth.missingAuthority',{authority:'PROC.SUPPLIER.PURCHASING.DISPLAY'})}</p>:!buyingChoices?.selected?<p className="panel p-4">{t('sp.noOrg')}</p>:<SupplierPurchasingPanel key={`${g!.partnerNumber}/${org}`} partner={g!.partnerNumber} org={org} company={buyingChoices.selected.companyCode} initial={{orderCurrency:purchasingRecord?purchasingRecord.orderCurrency??'':buyingChoices.selected.currency,purchasingGroup:purchasingRecord?.purchasingGroup??'',incotermsCode:purchasingRecord?.incotermsCode??'',incotermsLocation:purchasingRecord?.incotermsLocation??'',paymentTermsCode:purchasingRecord?.paymentTermsCode??'',isBlocked:purchasingRecord?.isBlocked??false,version:purchasingRecord?.version??0,purchasingStatus:purchasingRecord?.purchasingStatus??'INCOMPLETE'}} currencies={buyingChoices.currencies} groups={buyingChoices.groups} terms={buyingChoices.terms} deliveryCodes={DELIVERY_TERMS} editable={purchasingEditable}/>}</>}
    {customerView&&<><form method="get" className="flex items-end gap-2"><input type="hidden" name="partner" value={g!.partnerNumber}/><input type="hidden" name="view" value="CUSTOMER_COMPANY"/><label><span className="field-label">{t('sc.company')}</span><select name="company" defaultValue={customerCode} className="field-input">{receivableChoices?.companies.map(row=><option key={row.code} value={row.code}>{row.code} · {row.name}</option>)}</select></label><button className="btn btn-default">{t('sc.selectCompany')}</button></form>
      {!customerActive?<p className="panel p-4">{t('custco.roleRequired')}</p>:!customerReadable?<p className="panel p-4">{t('auth.missingAuthority',{authority:'FIN.CUSTOMER.COMPANY.DISPLAY'})}</p>:!receivableChoices?.selected?<p className="panel p-4">{t('sc.noCompany')}</p>:<CustomerCompanyPanel key={`${g!.partnerNumber}/${customerCode}`} partner={g!.partnerNumber} company={customerCode} initial={{reconciliationAccount:customerRecord?.reconciliationAccount??'',paymentTermsCode:customerRecord?.paymentTermsCode??'',isBlocked:customerRecord?.isBlocked??false,version:customerRecord?.version??0,companyStatus:customerRecord?.companyStatus??'INCOMPLETE'}} chart={receivableChoices.selected.chartOfAccounts} currency={receivableChoices.selected.currency} accounts={receivableChoices.accounts} terms={receivableChoices.terms} editable={customerEditable}/>}</>}
    {salesView&&<><form method="get" className="flex items-end gap-2"><input type="hidden" name="partner" value={g!.partnerNumber}/><input type="hidden" name="view" value="CUSTOMER_SALES"/><label><span className="field-label">{t('csa.area')}</span><select name="area" defaultValue={salesKey} className="field-input">{salesChoices?.areas.map(row=><option key={row.key} value={row.key}>{row.org} / {row.channel} / {row.division} · {row.name}</option>)}</select></label><button className="btn btn-default">{t('csa.selectArea')}</button></form>
      {!customerActive?<p className="panel p-4">{t('csa.roleRequired')}</p>:!salesReadable?<p className="panel p-4">{t('auth.missingAuthority',{authority:'SALES.CUSTOMER.SALESAREA.DISPLAY'})}</p>:!salesChoices?.selected?<p className="panel p-4">{t('csa.noArea')}</p>:<CustomerSalesAreaPanel key={`${g!.partnerNumber}/${salesKey}`} partner={g!.partnerNumber} area={{org:salesChoices.selected.org,channel:salesChoices.selected.channel,division:salesChoices.selected.division,name:salesChoices.selected.name,organisation:salesChoices.selected.organisation,companyCode:salesChoices.selected.companyCode,currency:salesChoices.selected.currency}} initial={{deliveringPlant:salesRecord?.deliveringPlant??'',pricingProcedure:salesRecord?.pricingProcedure??'',salesDistrict:salesRecord?.salesDistrict??'',completeDelivery:salesRecord?.completeDelivery??false,orderCombination:salesRecord?.orderCombination??false,isBlocked:salesRecord?.isBlocked??false,version:salesRecord?.version??0,salesStatus:salesRecord?.salesStatus??'INCOMPLETE'}} plants={salesChoices.plants} editable={salesEditable}/>}</>}
    {!creating&&!detail&&<><form method="get" className="flex items-end gap-2"><label><span className="field-label">{t('bp.search')}</span><input name="q" defaultValue={params.q} className="field-input"/></label><button className="btn btn-default">{t('registry.search')}</button></form><section className="panel overflow-x-auto"><table className="grid-table"><thead><tr>{['bp.number','bp.name','bp.category','bp.country','bp.city','bp.status','bp.version'].map(key=><th key={key}>{t(key)}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.partnerNumber}><td><Link className="code text-accent underline" href={`/foundation/partners?partner=${encodeURIComponent(row.partnerNumber)}${params.view==='SUPPLIER_COMPANY'?'&view=SUPPLIER_COMPANY':params.view==='SUPPLIER_PURCHASING'?'&view=SUPPLIER_PURCHASING':params.view==='CUSTOMER_COMPANY'?'&view=CUSTOMER_COMPANY':params.view==='CUSTOMER_SALES'?'&view=CUSTOMER_SALES':''}`}>{row.partnerNumber}</Link></td><td>{row.name||'—'}</td><td>{t(`bp.category.${row.category}`)}</td><td>{row.country||'—'}</td><td>{row.city||'—'}</td><td>{t(`bp.status.${row.isBlocked?'BLOCKED':row.generalStatus}`)}</td><td>{row.version}</td></tr>)}</tbody></table>{!rows.length&&<p className="p-4">{t('bp.empty')}</p>}<p className="border-t border-line p-2 text-2xs text-ink-soft">{t('bp.listLimit')}</p></section></>}
    {detail&&params.history==='1'&&<section className="panel"><h2 className="panel-header panel-title">{t('bp.history')}</h2>{history.map(entry=><article key={entry.id} className="border-b border-line p-3 text-sm"><p>{entry.changedAt.toISOString()} · {entry.changedBy} · {entry.changeType}</p><p>{entry.reason}</p><ul className="mt-1 text-2xs">{entry.items.map(item=><li key={item.id}>{item.fieldLabel}: {item.oldValue??'—'} → {item.newValue??'—'}{item.isSecurityRelevant==='true'?` · ${t('nr.controlChange')}`:''}</li>)}</ul></article>)}</section>}
  </div>;
}
function Summary({label,value}:{label:string;value:string}){return <div><p className="field-label">{label}</p><p>{value}</p></div>;}
