import Link from 'next/link';
import { requireSession, can } from '@/platform/auth/current';
import { t } from '@/platform/i18n';
import { listPaymentTerms, getPaymentTerms, type PaymentTermValues } from '@/modules/foundation/payment-terms';
import { calculatePaymentSchedule, type BaselineSource } from '@/modules/foundation/payment-term-dates';
import { withTenant } from '@/platform/db/client';
import { changeHistory } from '@/platform/change';
import { TermsForm } from './TermsForm';
export const dynamic='force-dynamic';
export default async function PaymentTermsPage({searchParams}:{searchParams:Promise<{code?:string;new?:string;q?:string;baseline?:string;history?:string}>}){
  const session=await requireSession('/config/payment-terms');const client=session.user.client;const params=await searchParams;
  const editable=can(session,'CFG.FIN.PAYTERMS.DEFINE');const creating=params.new==='1';
  const detail=params.code?await getPaymentTerms(client,params.code):null;
  const rows=!detail&&!creating?(await listPaymentTerms(client)).filter((row)=>!params.q||`${row.termsCode} ${row.description}`.toLowerCase().includes(params.q.toLowerCase())):[];
  const initial:PaymentTermValues=detail?{termsCode:detail.termsCode,description:detail.description,baselineSource:detail.baselineSource as BaselineSource,netDays:detail.netDays,discount1Days:detail.discount1Days,discount1Percent:detail.discount1Percent,discount2Days:detail.discount2Days,discount2Percent:detail.discount2Percent,isActive:detail.isActive}:{termsCode:'',description:'',baselineSource:'DOCUMENT_DATE',netDays:30,discount1Days:null,discount1Percent:'0.00',discount2Days:null,discount2Percent:'0.00',isActive:true};
  const baseline=params.baseline??new Date().toISOString().slice(0,10);
  let preview:ReturnType<typeof calculatePaymentSchedule>|undefined;let previewError='';
  if(detail){try{preview=calculatePaymentSchedule({...detail,baselineSource:detail.baselineSource as BaselineSource},{[detail.baselineSource]:baseline});}catch{previewError=t('pt.invalidDate');}}
  const history=detail&&params.history==='1'?await withTenant(client,(tx)=>changeHistory(tx,client,'payment_terms',detail.termsCode)):[];
  return <div className="mx-auto max-w-6xl space-y-4 p-6">
    <header className="border-b border-line pb-4"><span className="code text-ink-faint">CFG.FIN.PAYTERMS.DEFINE</span><div className="flex flex-wrap items-center justify-between gap-3"><h1 className="text-xl font-semibold">{t('pt.title')}</h1><div className="flex gap-2"><Link className="btn btn-default" href="/config">{t('nav.workbench')}</Link><Link className="btn btn-default" href="/config/payment-terms">{t('pt.list')}</Link>{editable&&!creating&&<Link className="btn btn-primary" href="/config/payment-terms?new=1">{t('pt.create')}</Link>}</div></div><p className="mt-1 text-sm text-ink-soft">{t('pt.subtitle')}</p></header>
    {params.code&&!detail&&<p className="panel p-4 text-signal-error">{t('pt.notFound')}</p>}
    {(creating||detail)&&(editable?<TermsForm key={creating?'new':detail!.termsCode} initial={initial} version={detail?.version??0} creating={creating}/>:<section className="panel p-4"><p>{t('auth.readOnly',{authority:'CFG.FIN.PAYTERMS.DEFINE'})}</p>{detail&&<dl className="mt-3 grid gap-2 sm:grid-cols-3">{Object.entries(initial).filter(([k])=>!['client','createdBy','changedBy','createdAt','changedAt'].includes(k)).map(([key,value])=><div key={key}><dt className="field-label">{t(`pt.field.${key}`)}</dt><dd>{String(value??'—')}</dd></div>)}</dl>}</section>)}
    {!creating&&!detail&&<><form method="get" className="flex items-end gap-2"><label><span className="field-label">{t('pt.search')}</span><input name="q" defaultValue={params.q} className="field-input" /></label><button className="btn btn-default">{t('registry.search')}</button></form><section className="panel overflow-x-auto"><table className="grid-table"><thead><tr>{['pt.code','pt.description','pt.baseline','pt.netDays','pt.active','pt.version'].map((key)=><th key={key}>{t(key)}</th>)}</tr></thead><tbody>{rows.map((row)=><tr key={row.termsCode}><td><Link className="code text-accent underline" href={`/config/payment-terms?code=${encodeURIComponent(row.termsCode)}`}>{row.termsCode}</Link></td><td>{row.description}</td><td>{t(`pt.baseline.${row.baselineSource}`)}</td><td>{row.netDays}</td><td>{t(row.isActive?'pt.yes':'pt.no')}</td><td>{row.version}</td></tr>)}</tbody></table>{!rows.length&&<p className="p-4">{t('pt.empty')}</p>}</section></>}
    {detail&&<section className="panel p-4"><div className="flex justify-between"><h2 className="panel-title">{t('pt.preview')}</h2><Link className="text-sm text-accent underline" href={`/config/payment-terms?code=${encodeURIComponent(detail.termsCode)}&history=1`}>{t('pt.history')}</Link></div><form method="get" className="mt-3 flex items-end gap-2"><input type="hidden" name="code" value={detail.termsCode}/><label><span className="field-label">{t('pt.baselineDate')}</span><input name="baseline" type="date" required defaultValue={baseline} className="field-input" /></label><button className="btn btn-default">{t('pt.previewButton')}</button></form>{previewError&&<p className="mt-2 text-signal-error">{previewError}</p>}{preview&&<div className="mt-3 text-sm"><p>{t('pt.netDue')}: <strong>{preview.netDueDate}</strong></p>{preview.discounts.map((discount,i)=><p key={i}>{t('pt.discountDeadline',{level:String(i+1)})}: {discount.untilDate} · {discount.percent}%</p>)}<p className="mt-2 text-2xs text-ink-soft">{t('pt.previewNote',{version:String(preview.termsVersion)})}</p></div>}</section>}
    {detail&&params.history==='1'&&<section className="panel"><h2 className="panel-header panel-title">{t('pt.history')}</h2>{history.map((entry)=><article key={entry.id} className="border-b border-line p-3 text-sm"><p>{entry.changedAt.toISOString()} · {entry.changedBy} · {entry.changeType}</p><p>{entry.reason}</p><ul className="mt-1 text-2xs">{entry.items.map((item)=><li key={item.id}>{item.fieldLabel}: {item.oldValue??'—'} → {item.newValue??'—'}{item.isSecurityRelevant==='true'?` · ${t('nr.controlChange')}`:''}</li>)}</ul></article>)}</section>}
  </div>;
}
